export const map2str = (num: number) => (num >= 0) ? MAPS[num] ?? `Map ${num}` : 'undefined'
export const MAPS: Record<number, string> = {
    1: `Old Summoner's Rift`,
    3: `Proving Grounds`,
    8: `Crystal Scar`,
    10: `Twisted Treeline`,
    11: `Summoner's Rift`,
    12: `Howling Abyss`,
    13: `Magma Chamber`,
    14: `Butcher's Bridge`,
    16: `Cosmic Ruins`,
    18: `Valoran City Park`,
    19: `Substructure 43`,
    20: `Crash Site`,
    21: `Temple of Lily and Lotus`,
    30: `Arena: Rings of Wrath`,
    35: `The Bandlewood`,
} //as const

export const mode2str = (num: number) => (num >= 0) ? MODES[num] ?? `Mode ${num}` : 'undefined'
export const MODES: Record<number, string> = {
    1: 'CLASSIC',
    2: 'ARAM',
} //as const

export const COLOR_NAMES = [ 'blue', 'red', 'green', 'yellow', 'magenta', 'cyan', 'white' ] as const
export const team2color = (team: number): (typeof COLOR_NAMES)[number] | 'gray' => {
    return (team >= 0) ? COLOR_NAMES[team] ?? 'white' : 'gray'
}

export const champ2str = (num: number) => (num >= 0) ? CHAMPIONS[num] ?? `Champion ${num}` : 'undefined'
export const CHAMPIONS = [
    "Alistar",
    "Annie",
    "Ashe",
    "Fiddlesticks",
    "Jax",
    "Kayle",
    "Master Yi",
    "Morgana",
    "Nunu & Willump",
    "Ryze",
    "Sion",
    "Sivir",
    "Soraka",
    "Teemo",
    "Tristana",
    "Twisted Fate",
    "Warwick",
    "Singed",
    "Zilean",
    "Evelynn",
    "Tryndamere",
    "Twitch",
    "Karthus",
    "Amumu",
    "Cho'Gath",
    "Anivia",
    "Rammus",
    "Veigar",
    "Kassadin",
    "Gangplank",
    "Taric",
    "Blitzcrank",
    "Dr. Mundo",
    "Janna",
    "Malphite",
    "Corki",
    "Katarina",
    "Nasus",
    "Heimerdinger",
    "Shaco",
    "Udyr",
    "Nidalee",
    "Poppy",
    "Gragas",
    "Pantheon",
    "Mordekaiser",
    "Ezreal",
    "Shen",
    "Kennen",
    "Garen",
    "Akali",
    "Malzahar",
    "Olaf",
    "Kog'Maw",
    "Xin Zhao",
    "Vladimir",
    "Galio",
    "Urgot",
    "Miss Fortune",
    "Sona",
    "Swain",
    "Lux",
    "LeBlanc",
    "Irelia",
    "Trundle",
    "Cassiopeia",
    "Caitlyn",
    "Renekton",
    "Karma",
    "Maokai",
    "Jarvan IV",
    "Nocturne",
    "Lee Sin",
    "Brand",
    "Rumble",
    "Vayne",
    "Orianna",
    "Yorick",
    "Leona",
    "Wukong",
    "Skarner",
    "Talon",
    "Riven",
    "Xerath",
    "Graves",
    "Shyvana",
    "Fizz",
    "Volibear",
    "Ahri",
    "Viktor",
    "Sejuani",
    "Ziggs",
    "Nautilus",
    "Fiora",
    "Lulu",
    "Hecarim",
    "Varus",
    "Darius",
    "Draven",
    "Jayce",
    "Zyra",
    "Diana",
    "Rengar",
    "Syndra",
    "Kha'Zix",
    "Elise",
    "Zed",
    "Nami",
    "Vi",
    "Thresh",
    "Quinn",
    "Zac",
    "Lissandra",
    "Aatrox",
    "Lucian",
    "Jinx",
    "Yasuo",
    "Vel'Koz",
    "Braum",
    "Gnar",
    "Azir",
    "Kalista",
    "Rek'Sai",
    "Bard",
    "Ekko",
    "Tahm Kench",
    "Kindred",
    "Illaoi",
    "Jhin",
    "Aurelion Sol",
    "Taliyah",
    "Kled",
    "Ivern",
    "Camille",
    "Rakan",
    "Xayah",
    "Kayn",
    "Ornn",
    "Zoe",
    "Kai'Sa",
    "Pyke",
    "Neeko",
    "Sylas",
    "Yuumi",
    "Qiyana",
    "Senna",
    "Aphelios",
    "Sett",
    "Lillia",
    "Yone",
    "Samira",
    "Seraphine",
    "Rell",
    "Viego",
    "Gwen",
    "Akshan",
    "Vex",
    "Zeri",
    "Renata Glasc",
    "Bel'Veth",
    "Nilah",
    "K'Sante",
    "Milio",
    "Naafiri",
    "Briar",
    "Hwei",
    "Smolder",
    "Aurora",
    "Ambessa",
    "Mel",
] //as const

export const sspell2str = (num: number) => (num >= 0) ? SUMMONER_SPELLS[num] ?? `Summoner Spell ${num}` : 'undefined'
export const SUMMONER_SPELLS = [
    "Heal",
    "Ghost",
    "Barrier",
    "Exhaust",
    "Mark",
    "Dash",
    "Clarity",
    "Flash",
    "Teleport",
    "Smite",
    "Cleanse", 
    "Ignite"
] //as const

export const team2str = (num: number) => (num >= 0) ? TEAMS[num] ?? `Team ${num}` : 'undefined'
export const TEAMS = [
    "Blue", "Purple", "Neutral",
]

export const lock2str = (num: number) => (num > 0) ? 'Locked' : 'Unlocked'
export const LOCK = [ "Unlocked", "Locked" ]

export enum PlayerPickableProp {
    Team = 0,
    Champion = 1,
    SummonerSpell1 = 2,
    SummonerSpell2 = 3,
    Lock = 4,
}

export const ppp2str = (prop: PlayerPickableProp) => PLAYER_PICKABLE_PROPS_NAMES[prop]!
const PLAYER_PICKABLE_PROPS_NAMES = [
    'Team',
    'Champion',
    'Summoner Spell 1',
    'Summoner Spell 2',
    'Lock',
]

export const PLAYER_PICKABLE_PROPS: Record<PlayerPickableProp, string[]> = {
    [PlayerPickableProp.Team]: TEAMS,
    [PlayerPickableProp.Champion]: CHAMPIONS,
    [PlayerPickableProp.SummonerSpell1]: SUMMONER_SPELLS,
    [PlayerPickableProp.SummonerSpell2]: SUMMONER_SPELLS,
    [PlayerPickableProp.Lock]: LOCK,
}
//export type PlayerPickablePropKeys = Uncapitalize<keyof typeof PlayerPickableProp>
export const PLAYER_PICKABLE_PROPS_KEYS:
(keyof typeof PLAYER_PICKABLE_PROPS)[] = [
    PlayerPickableProp.Team,
    PlayerPickableProp.Champion,
    PlayerPickableProp.SummonerSpell1,
    PlayerPickableProp.SummonerSpell2,
    PlayerPickableProp.Lock,
]