export const MAPS: Record<number, string> = {
    0: `Unspecified`,
    1: `Old Summoner's Rift`,
    3: `Proving Grounds`,
    8: `Crystal Scar`,
    10: `Twisted Treeline`,
    11: `Summoner's Rift`,
    12: `Howling Abyss`,
    13: `Magma Chamber`,
    14: `Butcher's Bridge`,
    16: `Cosmic Ruins`,
    18: `Valoran City Park`,
    19: `Substructure 43`,
    20: `Crash Site`,
    21: `Temple of Lily and Lotus`,
    30: `Arena: Rings of Wrath`,
    35: `The Bandlewood`,
} as const
export const map2str = (num: number) => MAPS[num] || `Map ${num}`

export const MODES: Record<number, string> = {
    0: 'Unspecified',
    1: 'CLASSIC',
    2: 'ARAM',
} as const
export const mode2str = (num: number) => MODES[num] || `Mode ${num}`

export const COLOR_NAMES = [ 'blue', 'red', 'gray', 'green', 'yellow', 'magenta', 'cyan' ] as const
export const team2color = (team: number): (typeof COLOR_NAMES)[number] => {
    return COLOR_NAMES[team]!
}

export const CHAMPIONS = [
    'Unspecified',
    "Alistar",
    "Annie",
    "Ashe",
    "Fiddlesticks",
    "Jax",
    "Kayle",
    "Master Yi",
    "Morgana",
    "Nunu & Willump",
    "Ryze",
    "Sion",
    "Sivir",
    "Soraka",
    "Teemo",
    "Tristana",
    "Twisted Fate",
    "Warwick",
    "Singed",
    "Zilean",
    "Evelynn",
    "Tryndamere",
    "Twitch",
    "Karthus",
    "Amumu",
    "Cho'Gath",
    "Anivia",
    "Rammus",
    "Veigar",
    "Kassadin",
    "Gangplank",
    "Taric",
    "Blitzcrank",
    "Dr. Mundo",
    "Janna",
    "Malphite",
    "Corki",
    "Katarina",
    "Nasus",
    "Heimerdinger",
    "Shaco",
    "Udyr",
    "Nidalee",
    "Poppy",
    "Gragas",
    "Pantheon",
    "Mordekaiser",
    "Ezreal",
    "Shen",
    "Kennen",
    "Garen",
    "Akali",
    "Malzahar",
    "Olaf",
    "Kog'Maw",
    "Xin Zhao",
    "Vladimir",
    "Galio",
    "Urgot",
    "Miss Fortune",
    "Sona",
    "Swain",
    "Lux",
    "LeBlanc",
    "Irelia",
    "Trundle",
    "Cassiopeia",
    "Caitlyn",
    "Renekton",
    "Karma",
    "Maokai",
    "Jarvan IV",
    "Nocturne",
    "Lee Sin",
    "Brand",
    "Rumble",
    "Vayne",
    "Orianna",
    "Yorick",
    "Leona",
    "Wukong",
    "Skarner",
    "Talon",
    "Riven",
    "Xerath",
    "Graves",
    "Shyvana",
    "Fizz",
    "Volibear",
    "Ahri",
    "Viktor",
    "Sejuani",
    "Ziggs",
    "Nautilus",
    "Fiora",
    "Lulu",
    "Hecarim",
    "Varus",
    "Darius",
    "Draven",
    "Jayce",
    "Zyra",
    "Diana",
    "Rengar",
    "Syndra",
    "Kha'Zix",
    "Elise",
    "Zed",
    "Nami",
    "Vi",
    "Thresh",
    "Quinn",
    "Zac",
    "Lissandra",
    "Aatrox",
    "Lucian",
    "Jinx",
    "Yasuo",
    "Vel'Koz",
    "Braum",
    "Gnar",
    "Azir",
    "Kalista",
    "Rek'Sai",
    "Bard",
    "Ekko",
    "Tahm Kench",
    "Kindred",
    "Illaoi",
    "Jhin",
    "Aurelion Sol",
    "Taliyah",
    "Kled",
    "Ivern",
    "Camille",
    "Rakan",
    "Xayah",
    "Kayn",
    "Ornn",
    "Zoe",
    "Kai'Sa",
    "Pyke",
    "Neeko",
    "Sylas",
    "Yuumi",
    "Qiyana",
    "Senna",
    "Aphelios",
    "Sett",
    "Lillia",
    "Yone",
    "Samira",
    "Seraphine",
    "Rell",
    "Viego",
    "Gwen",
    "Akshan",
    "Vex",
    "Zeri",
    "Renata Glasc",
    "Bel'Veth",
    "Nilah",
    "K'Sante",
    "Milio",
    "Naafiri",
    "Briar",
    "Hwei",
    "Smolder",
    "Aurora",
    "Ambessa",
    "Mel",
]
export const SUMMONER_SPELLS = [
    'Unspecified',
    "Heal",
    "Ghost",
    "Barrier",
    "Exhaust",
    "Mark",
    "Dash",
    "Clarity",
    "Flash",
    "Teleport",
    "Smite",
    "Cleanse", 
    "Ignite"
]

export const PLAYER_PICKABLE_PROPS = {
    champion: CHAMPIONS,
    summonerSpell1: SUMMONER_SPELLS,
    summonerSpell2: SUMMONER_SPELLS,
} as const

export type PlayerPickableProp = keyof typeof PLAYER_PICKABLE_PROPS
export const PLAYER_PICKABLE_PROPS_KEYS = Object.keys(PLAYER_PICKABLE_PROPS) as PlayerPickableProp[]
export const ppp2int = (ppp: PlayerPickableProp) => {
    return PLAYER_PICKABLE_PROPS_KEYS.indexOf(ppp) + 1
}
export const int2ppp = (int: number) => {
    if(int > 0 && int <= PLAYER_PICKABLE_PROPS_KEYS.length)
        return PLAYER_PICKABLE_PROPS_KEYS[int - 1]!
    return undefined
}